### ISSUE TITLE
Error Fetching Username

### ISSUE THREAD

**Issue by RyouNagumo** [Nexure/RoSearcher#5]
Rosearcher used to work until it suddenly stopped, whenever I use it, it says "Error occurred while fetching username!" hasn't fixed itself for months might have to do with roblox updating
I am currently using a macOS high sierra

**Comment by Nexure** [comment]
This is fixed, ROBLOX changed and the extension has been updated accordingly

**Comment by Desrokter** [comment]
![image](https://user-images.githubusercontent.com/62212300/76705018-3bff7d00-66b3-11ea-9ed9-73c96e136813.png)
This still happens when I try to search for somebodies username.

**Comment by YigitGuzel** [comment]
Error occured while fetching username!

i only get this massage
